apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: apis-orchestrator
  namespace: creditai
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apis-orchestrator
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
